package MD5;
import java.math.BigInteger;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;

//implementation of md5 hashing algorithm
public class MD5 {
    public static String hash(String input)
    {
        try {

            MessageDigest md = MessageDigest.getInstance("MD5");

            //calculate message digest.
            //returns byte array
            byte[] messageDigest = md.digest(input.getBytes());

            //convert byte array into BigInt
            BigInteger num = new BigInteger(1, messageDigest);

            //convert message digest into hex value
            String hashtext = num.toString(16);
            while (hashtext.length() < 32) {
                hashtext = "0" + hashtext;
            }
            return hashtext;
        }

        //wrong message digest algorithm provided
        catch (NoSuchAlgorithmException e) {
            throw new RuntimeException(e);
        }
    }

    // Testing for Broker.CalculateKeys()
    public static void main(String args[]) throws NoSuchAlgorithmException
    {
        //testing the hash function
        String input = "This is a test";
        System.out.println("Your HashCode Generated by MD5.MD5 is: " + hash(input));

        //modulo 3 of output (for load distribution between brokers)
        String a = hash(input);
        //convert hash(input) from hex back to binary
        BigInteger b = new BigInteger(a,16);
        BigInteger c = b.mod(BigInteger.valueOf(3));
        System.out.println(c);
    }
}
