package com.simplegram.src.MD5;
import java.math.BigInteger;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;

//implementation of md5 hashing algorithm
public class MD5 {
    public static String hash(String input)
    {
        try {

            MessageDigest md = MessageDigest.getInstance("MD5");

            //calculate message digest.
            //returns byte array
            byte[] messageDigest = md.digest(input.getBytes());

            //convert byte array into BigInt
            BigInteger num = new BigInteger(1, messageDigest);

            //convert message digest into hex value
            String hashtext = num.toString(16);
            while (hashtext.length() < 32) {
                hashtext = "0" + hashtext;
            }
            return hashtext;
        }

        //wrong message digest algorithm provided
        catch (NoSuchAlgorithmException e) {
            throw new RuntimeException(e);
        }
    }

    // Testing for Broker.CalculateKeys()
    public static void main(String args[]) throws NoSuchAlgorithmException
    {
        //testing the hash function
        String input = "Some Topic Name";
        String a = hash(input);
        System.out.println("Your HashCode generated by MD5 is: " + a);

        //convert hash(input) from hex to decimal
        BigInteger b = new BigInteger(a,16);
        System.out.println(b);
        //calculate the modulo 300 value (used for load distribution between Brokers)
        BigInteger c = b.mod(BigInteger.valueOf(300));
        System.out.println(c);
    }
}
